# Generated by Django 4.0.3 on 2022-07-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminManagement', '0002_initial'),
        ('PaymentManagement', '0001_initial'),
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='clienteid',
            field=models.ForeignKey(blank=True, db_column='ClienteID', null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizadores.cliente'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='pagamentoid',
            field=models.ForeignKey(blank=True, db_column='PagamentoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.pagamento'),
        ),
        migrations.AddField(
            model_name='dia',
            name='periodicidadeid',
            field=models.ForeignKey(db_column='Periodicidade', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.periodicidade'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clienteid',
            field=models.ForeignKey(db_column='ClienteID', default=1, on_delete=django.db.models.deletion.CASCADE, to='utilizadores.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminManagement.parque'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='periodicidadeid',
            field=models.ForeignKey(db_column='PeriodicidadeID', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.periodicidade'),
        ),
    ]
