# Generated by Django 4.0.3 on 2022-07-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PaymentManagement', '0001_initial'),
        ('OperationManagement', '0001_initial'),
        ('AdminManagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='contratoid',
            field=models.ForeignKey(db_column='ContratoID', null=True, on_delete=django.db.models.deletion.CASCADE, to='PaymentManagement.contrato'),
        ),
        migrations.AddField(
            model_name='viatura',
            name='registo_movimentoid',
            field=models.ForeignKey(db_column='Registo-movimentoID', on_delete=django.db.models.deletion.CASCADE, to='OperationManagement.registomovimento'),
        ),
        migrations.AddField(
            model_name='registomovimento',
            name='parqueid',
            field=models.ForeignKey(db_column='ParqueID', default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminManagement.parque'),
        ),
    ]
